### ISSUE TITLE
Université de Saint-Boniface

### ISSUE THREAD

**Issue by pjohanneson** [endSly/world-universities-csv#2]
"University College of Saint Boniface" -- `http://www.ustboniface.ca` -- is now named "Université de Saint-Boniface", having become a full-fledged university in Sept. 2011.

https://en.wikipedia.org/wiki/Universit%C3%A9_de_Saint-Boniface

**Comment by jonny-no1** [comment]
I'd suggest you add it to univ.cc which is the source of this project http://univ.cc/add.php

**Comment by pjohanneson** [comment]
Done, thanks.
