### ISSUE TITLE
Special characters in CSV

### ISSUE THREAD

**Issue by databasegeek** [endSly/world-universities-csv#8]
Sorry if I'm being stupid, but when I open the CSV I'm getting lot of special characters that don't look right. Am I doing something wrong? For example:
![image](https://cloud.githubusercontent.com/assets/25979665/23256686/7aa0b21a-f9b8-11e6-9ad1-ccb40462a8b3.png)

**Comment by endikag** [comment]
CSV is encoded in UTF-8

**Comment by databasegeek** [comment]
Thanks a million! 👍
